## Series와 DataFrame

- Series = 1차원 데이터 + 인덱스(라벨). 엑셀의 한 열
- DataFrame = 2차원 표. 여러 Series(열)가 같은 인덱스를 공유

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__) # 버전 확인

3.0.3

In [3]:
# 리스트 만들기
s = pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
s2 = pd.Series([90, 85, 88], index=["국어", "영어", "수학"])
print(s2)

print(s2["영어"])
print(s2.values)
print(s2.index)

국어    90
영어    85
수학    88
dtype: int64
85
[90 85 88]
Index(['국어', '영어', '수학'], dtype='str')

In [7]:
# DataFrame 만들어보기

df = pd.DataFrame({
    "이름": ["철수", "영희", "민수"],
    "나이": [25, 30, 28],
    "도시": ["서울", "부산", "서울"],
})
print(df)

   이름  나이  도시
0  철수  25  서울
1  영희  30  부산
2  민수  28  서울

In [14]:
df.shape

(3, 3)

In [15]:
df.columns

Index(['이름', '나이', '도시'], dtype='str')

In [16]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [17]:
df.dtypes

이름      str
나이    int64
도시      str
dtype: object

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      str
 1   나이      3 non-null      int64
 2   도시      3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [19]:
df.head(2)

   이름  나이  도시
0  철수  25  서울
1  영희  30  부산

In [22]:
## 미니 과제
fruites = pd.Series([3000, 5000, 8000], index=["멜론","수박","바나나"])

df["나이"]
type(df["나이"])

pandas.Series

In [23]:
df.describe()

              나이
count   3.000000
mean   27.666667
std     2.516611
min    25.000000
25%    26.500000
50%    28.000000
75%    29.000000
max    30.000000